/* fonts */
export const FontFamily = {
  materialThemeDisplayLarge: "Roboto-Regular",
  androidTextStylesHeadingBold: "Roboto-Bold",
  iBMPlexSansRegular: "IBMPlexSans-Regular",
  iBMPlexSansCondSemiBold: "IBMPlexSansCond-SemiBold",
  iBMPlexSansMedium: "IBMPlexSans-Medium",
  androidTextStylesBodySmallSemibold: "Roboto-Medium",
  figmaKitKitSubtitle: "Manrope-Bold",
  figmaKitKitBody: "Manrope-Medium",
  figmaKitKitLargeTitle: "Manrope-ExtraBold",
};
/* font sizes */
export const FontSize = {
  figmaKitKitBody_size: 16,
  materialThemeHeadlineSmall_size: 24,
  materialThemeLabelLarge_size: 14,
  materialThemeTitleLarge_size: 22,
  androidTextStylesBodySmallSemibold_size: 12,
  figmaKitKitLargeTitle_size: 56,
  materialThemeDisplayLarge_size: 57,
  materialThemeHeadlineMedium_size: 28,
  materialThemeLabelSmall_size: 11,
  materialThemeHeadlineLarge_size: 32,
  androidTextStylesCaptionSemibold_size: 10,
};
/* Colors */
export const Color = {
  materialThemeSysLightSurfaceBright: "#fff9ec",
  colorDarkturquoise: "#05c5cf",
  materialThemeSysLightTertiary: "#426650",
  materialThemeSysLightOnSurfaceVariant: "#4a4739",
  materialThemeSysDarkTertiaryContainer: "#2a4e39",
  materialThemeSysDarkSurfaceBright: "#3c3930",
  materialThemeSysDarkSurfaceContainerHighest: "#37352b",
  materialThemeSysDarkOnSecondary: "#363116",
  materialThemeSysDarkOnTertiary: "#133724",
  materialThemeSysDarkOutline: "#969180",
  materialThemeSysLightOutline: "#7b7768",
  materialThemeSysDarkSurfaceContainerHigh: "#2c2a21",
  materialThemeSysDarkSurfaceContainer: "#222017",
  materialThemeSysLightOnSurface: "#1e1c13",
  materialThemeSysLightOnSecondaryContainer: "#201c04",
  materialThemeSysLightOnPrimaryContainer: "#211b00",
  colorGray_100: "#14181f",
  materialThemeSysLightOnTertiaryContainer: "#002111",
  materialThemeSysDarkSurfaceDim: "#15130c",
  materialThemeSysDarkSurfaceContainerLowest: "#100e07",
  materialThemeStateLayersLightOnSurfaceOpacity016: "rgba(30, 28, 19, 0.16)",
  systemScrim: "rgba(0, 0, 0, 0.4)",
  materialThemeStateLayersLightOnSurfaceOpacity008: "rgba(30, 28, 19, 0.08)",
  materialThemeStateLayersLightOnPrimaryContainerOpacity008:
    "rgba(33, 27, 0, 0.08)",
  materialThemeStateLayersLightOnSurfaceOpacity012: "rgba(30, 28, 19, 0.12)",
  materialThemeStateLayersLightOnPrimaryContainerOpacity012:
    "rgba(33, 27, 0, 0.12)",
  colorGray_200: "rgba(20, 24, 31, 0.2)",
  colorLightslategray_100: "#8e9cb8",
  colorLightslategray_200: "rgba(142, 156, 184, 0.6)",
  materialThemeSysLightOnPrimary: "#fff",
  materialThemeSysLightSurfaceContainerHighest: "#e8e2d4",
  materialThemeSysLightSurfaceVariant: "#e9e2d0",
  materialThemeSysLightError: "#ba1a1a",
  materialThemeSysLightPrimary: "#6b5e10",
  materialThemeSysDarkPrimaryContainer: "#524700",
  materialThemeSysDarkOnPrimary: "#383000",
  materialThemeStateLayersLightPrimaryOpacity012: "rgba(107, 94, 16, 0.12)",
  materialThemeStateLayersLightPrimaryOpacity008: "rgba(107, 94, 16, 0.08)",
  materialThemeSysLightSurfaceContainerLow: "#f9f3e5",
  materialThemeSysLightInverseOnSurface: "#f6f0e2",
  materialThemeSysDarkOnTertiaryContainer: "#c4ecd0",
  materialThemeSysDarkOnPrimaryContainer: "#f5e388",
  materialThemeSysLightOutlineVariant: "#ccc6b5",
  materialThemeSysDarkOnSecondaryContainer: "#ede3bc",
  materialThemeStaticAutoTint: "#ff0000",
  materialThemeSysLightSurfaceContainer: "#f4ede0",
  materialThemeSysLightSurfaceContainerHigh: "#eee8da",
  materialThemeBlack: "#000",
  materialThemeSysDarkOnErrorContainer: "#ffdad6",
  materialThemeSysDarkErrorContainer: "#93000a",
  materialThemeSysDarkOnError: "#690005",
  materialThemeSysLightOnErrorContainer: "#410002",
  materialThemeSysDarkError: "#ffb4ab",
  materialThemeSysDarkSecondary: "#d0c7a2",
  materialThemeSysDarkTertiary: "#a8d0b5",
  materialThemeSysLightSecondary: "#655f40",
  materialThemeSysDarkSecondaryContainer: "#4d472b",
  materialThemeSysDarkPrimary: "#d8c770",
  materialThemeSysLightSurfaceDim: "#dfdacc",
};
/* Style Variables */
export const StyleVariable = {
  accessibilityMinBtnWidth: 64,
  accessibilityMinTargetSize: 48,
  accessibilityMinTargetSize1: 48,
  accessibilityMinBtnWidth1: 64,
};
/* Paddings */
export const Padding = {
  p_3xs: 10,
  p_5xs: 8,
  p_xl: 20,
  p_xs: 12,
  p_5xl: 24,
  p_21xl: 40,
  p_6xs: 7,
  p_10xs: 3,
  p_8xs: 5,
  p_4xs: 9,
  p_13xl: 32,
  p_29xl: 48,
  p_9xs: 4,
  p_45xl: 64,
  p_base: 16,
  p_2xs: 11,
  p_41xl: 60,
  p_9xl: 28,
  p_37xl: 56,
  p_11xs: 2,
};
/* border radiuses */
export const Border = {
  br_9xs: 4,
  br_45xl: 64,
  br_base: 16,
  br_21xl: 40,
  br_13xl: 32,
  br_8xs: 5,
  br_10xs: 3,
  br_29xl: 48,
  br_5xs: 8,
  br_xl: 20,
};
